version: "3.8"

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend Service
  backend:
    build:
      context: ./Full-Stack-TodoList-Backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      - db
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: ./Full-Stack-TodoList-Frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    restart: unless-stopped
